
name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: installing python package 
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: installing python dependency
      run: pip install pycryptodome
    - name: running python file 
      run: python aes_encode.py "hello world"
    - name: uploading artifacts
      uses: actions/upload-artifact@v3
      with:
        name: output-artifact
        path: output.txt
    - name: show github token value
      run: echo "$github.token"
